crgsbr_homepage:
    pattern:  /
    defaults: { _controller: CRGSBRBundle:Default:accueil }
crgsbr_profil:
    pattern:  /profil
    defaults: { _controller: CRGSBRBundle:Default:profil }
crgsbr_liste_medicament:
    pattern:  /listeMedicament
    defaults: { _controller: CRGSBRBundle:GSBR:listeMedicament }
crgsbr_recherche_medicament:
    pattern:  /rechercheMedicament
    defaults: { _controller: CRGSBRBundle:GSBR:rechercheMedicament }
crgsbr_liste_praticien:
    pattern:  /listePraticien
    defaults: { _controller: CRGSBRBundle:GSBR:listePraticien }
crgsbr_recherche_praticien:
    pattern:  /recherchePraticien
    defaults: { _controller: CRGSBRBundle:GSBR:recherchePraticien }
crgsbr_consulter_visite:
    pattern:  /consulterVisite
    defaults: { _controller: CRGSBRBundle:GSBR:consulterVisite }
crgsbr_ajouter_visite:
    pattern:  /ajouterVisite
    defaults: { _controller: CRGSBRBundle:GSBR:ajouterVisite }